# Generated by Django 2.1.4 on 2018-12-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20181229_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
