# Generated by Django 2.1.4 on 2018-12-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20181229_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
