# Generated by Django 2.1.4 on 2019-01-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='optionA',
        ),
        migrations.RemoveField(
            model_name='question',
            name='optionB',
        ),
        migrations.RemoveField(
            model_name='question',
            name='optionC',
        ),
        migrations.RemoveField(
            model_name='question',
            name='optionD',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200),
        ),
    ]
