# Generated by Django 2.1.4 on 2019-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190119_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optionA',
            field=models.CharField(default='None of given', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='optionB',
            field=models.CharField(default='None of given', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='optionC',
            field=models.CharField(default='None of given', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='optionD',
            field=models.CharField(default='None of given', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='No answer selected', max_length=100),
        ),
    ]
