# Generated by Django 2.1.4 on 2019-01-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20190119_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
    ]
