# Generated by Django 2.1.4 on 2019-01-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_question_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(default=0)),
                ('name', models.CharField(default='No Name', max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
