# Generated by Django 2.1.4 on 2019-01-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='roll',
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
