# Generated by Django 2.1.4 on 2019-01-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20190120_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
