# Generated by Django 2.1.4 on 2019-01-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20190120_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('f1', models.TextField()),
                ('f2', models.TextField()),
                ('f3', models.TextField()),
                ('f4', models.TextField()),
                ('f5', models.TextField()),
            ],
        ),
    ]
